### ISSUE TITLE
DLA34 is too slow

### ISSUE THREAD

**Issue by zyl1336110861** [VISION-SJTU/PointAugmenting#11]
@weiwei0224 Hi, I tried the DLA34 model on RTX 3090 and I found that the speed of the segmentation is too slow(about 200+ms/6imgs), which is much slower than the speed in your paper(95ms). Is that normal?

**Comment by zyl1336110861** [comment]
Done, when you test the speed of the model, just change the double_flip to False in the config file. The speed of DLA34 is fine(<50ms on the RTX3090).

**Comment by Devoe-97** [comment]
> Done, when you test the speed of the model, just change the double_flip to False in the config file. The speed of DLA34 is fine(<50ms on the RTX3090).

Hi, could you tell me where is the DLA_34 model?
